- name: Set up passwordless SSH
  hosts: localhost
  gather_facts: no
  vars:
    remote_hosts:
      - { host: "remote_host_1", user: "ubuntu" }
      - { host: "remote_host_2", user: "ubuntu" }
      - { host: "remote_host_3", user: "ec2-user" }

  tasks:
    - name: Generate ed25519 SSH Key Pair
      ansible.builtin.command: "ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''"
      args:
        creates: "~/.ssh/id_ed25519"

    - name: Copy Public Key to Remote Hosts
      ansible.builtin.command: "ssh-copy-id -i ~/.ssh/id_ed25519.pub {{ item.user }}@{{ item.host }}"
      with_items: "{{ remote_hosts }}"
