- name: Conditionally schedule daily shutdown on Ubuntu instances
  hosts: all
  become: yes
  vars:
    shutdown_time: "20:40"
    enable_shutdown: true

  tasks:
    - name: Parse shutdown hour and minute
      ansible.builtin.set_fact:
        shutdown_hour: "{{ shutdown_time.split(':')[0] }}"
        shutdown_minute: "{{ shutdown_time.split(':')[1] }}"

    - name: Set up a cron job to shut down the system at specified time
      ansible.builtin.cron:
        name: "Daily shutdown at {{ shutdown_time }}"
        minute: "{{ shutdown_minute }}"
        hour: "{{ shutdown_hour }}"
        job: "/sbin/shutdown -h now"
        state: present
      when:
        - enable_shutdown
        - ansible_hostname in ["ubuntu-1"]