---
- name: Deleting AWS EC2 Instances
  hosts: localhost
  connection: local
  vars:
    ec2_instance_ids:
      - i-09415117a754485b0
      - i-0936140cc0979097c
      - i-06a6dfa304c0c38fd

  tasks:
    - name: Terminate EC2 instances
      block:
        - name: Terminate individual EC2 instance
          amazon.aws.ec2_instance:
            region: us-east-1
            aws_access_key: "{{ aws_access_key }}"
            aws_secret_key: "{{ aws_secret_key }}"
            state: absent
            instance_ids: "{{ item }}"
          loop: "{{ ec2_instance_ids }}"
          register: termination_results
          loop_control:
            label: "Terminating instance {{ item }}"

      rescue:
        - name: Handle termination errors
          ansible.builtin.debug:
            msg: "Failed to terminate some instances. Check the error details."

      always:
        - name: Display termination results
          ansible.builtin.debug:
            var: termination_results
    
    - name: Delete SG
      amazon.aws.ec2_security_group:
        group_id: sg-04934f978b1c9c3f7
        state: absent