---
- hosts: localhost
  connection: local
  tasks:
    - name: Terminate an EC2 instance
      amazon.aws.ec2_instance:
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
        instance_ids: i-12324555